fix: Ensure target directories are not symlinks

diff --git a/configure/if-os/linux/enable-systemd-user b/configure/if-os/linux/enable-systemd-user
--- a/configure/if-os/linux/enable-systemd-user
+++ b/configure/if-os/linux/enable-systemd-user
@@ -2,6 +2,21 @@
 
 BASEDIR=${HOME}/.config/systemd/user
 
+DEFAULT_DIR="${XDG_CONFIG_HOME}/systemd/user/default.target.wants"
+TIMERS_DIR="${XDG_CONFIG_HOME}/systemd/user/timers.target.wants"
+
+mkdir -p "${DEFAULT_DIR}" "${TIMERS_DIR}"
+
+if [[ -h $DEFAULT_DIR ]]; then
+    echo >&2 "${DEFAULT_DIR} cannot be a symlink."
+    exit 1
+fi
+
+if [[ -h $TIMERS_DIR ]]; then
+    echo >&2 "${TIMERS_DIR} cannot be a symlink."
+    exit 1
+fi
+
 if [[ -d "${BASEDIR}" ]]; then
     for UNIT in "${BASEDIR}"/*.service; do
         UNIT_NOEXT="${UNIT%.*}"
diff --git a/configure/if-osdistribution/arch/additional-systemd-services b/configure/if-osdistribution/arch/additional-systemd-services
--- a/configure/if-osdistribution/arch/additional-systemd-services
+++ b/configure/if-osdistribution/arch/additional-systemd-services
@@ -2,5 +2,13 @@
 
 # Not installed in ~/.config/systemd/user
 
-systemctl enable --user --now mpd
-systemctl enable --user --now mpd-notification
+TARGET_DIR="${XDG_CONFIG_HOME}/systemd/user/default.target.wants"
+
+mkdir -p "$TARGET_DIR"
+
+if [ ! -h "${TARGET_DIR}" ]; then
+    systemctl enable --user --now mpd
+    systemctl enable --user --now mpd-notification
+else
+    echo >&2 "${TARGET_DIR} cannot be a symlink."
+fi
